INSERT INTO ROLE VALUES ('ROLE_ADMIN');
INSERT INTO ROLE VALUES ('ROLE_ORGANIZADOR');
INSERT INTO ROLE VALUES ('ROLE_TURISTA');

INSERT INTO USUARIO VALUES ('ADMIN', 0, '39293595885', 'admin@batevolta.com', 'HTTP', 'ADMIN', '$2a$10$ZZ09PypLo3AUWHr6iH8OuOJSP921c5HTUDv4vbT2PbePsKlDM2lQ2');
INSERT INTO USUARIOS_ROLES VALUES (0, 'ROLE_ADMIN');